[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\DanielLaury\ContextBridge\packages\backend\downloads\ContextBridge-VSCode-Setup.exe
FriendlyName=ContextBridge VS Code Extension Installer
AppLaunched=install-vscode.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="contextbridge-codex-0.0.1.vsix"
FILE1="install-vscode.bat"
[SourceFiles]
SourceFiles0=C:\Users\DanielLaury\ContextBridge\packages\vscode-extension\
[SourceFiles0]
%FILE0%=
%FILE1%=
