packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - puppeteer
  - tree-sitter
  - tree-sitter-go
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-rust
  - tree-sitter-typescript
