[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\DanielLaury\ContextBridge\packages\backend\downloads\ContextBridge-Chrome-Setup.exe
FriendlyName=ContextBridge Chrome Extension Installer
AppLaunched=install.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="background.js"
FILE1="content.js"
FILE2="content-universal.js"
FILE3="icon.png"
FILE4="install.bat"
FILE5="manifest.json"
FILE6="options.html"
FILE7="options.js"
FILE8="progress.html"
FILE9="progress.js"
[SourceFiles]
SourceFiles0=C:\Users\DanielLaury\ContextBridge\packages\chrome-extension\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
%FILE4%=
%FILE5%=
%FILE6%=
%FILE7%=
%FILE8%=
%FILE9%=
